DROP TABLE IF EXISTS assignment;
CREATE TABLE assignment (
	id INT(10) NOT NULL AUTO_INCREMENT,
	name VARCHAR( 40 ) NOT NULL,
	added_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	xml TEXT NOT NULL ,
	PRIMARY KEY (id)
);
